### ISSUE TITLE
Cannot play most videos due to lack of codecs

### ISSUE THREAD

**Issue by kdwk** [elementary/videos#281]
### What Happened?

After elementary OS 6 October updates, Videos is installed as a Flatpak and can no longer play videos, like the mp4 screencast I tested it with. 

When run with the Terminal, Videos throws this error: (io.elementary.videos:2): Gtk-WARNING **: 11:19:37.121: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node actionbar, owner GtkActionBar). 

The same video can be played by Clapper (Gtk4, Flatpak) without problem. I have installed the following runtimes: org.freedesktop.Platform.ffmpeg-full org.freedesktop.Platform.Gstreamer.gstreaner-vaapi org.freedesktop.Platform.openh264

### Steps to Reproduce

1. Install io.elementary.videos 2.8.0 branch stable from repo appcenter (system-wide)
2. Open an mp4 video

### Expected Behavior

Videos is able to play videos

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
(io.elementary.videos:2): Gtk-WARNING **: 11:19:37.121: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node actionbar, owner GtkActionBar)
```

### Hardware Info

CPU: Intel Core i7-9700

GPU: Intel UHD 630

`flatpak run org.freedesktop.Platform.VaInfo`: 
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.12 (libva 2.9.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.3.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD

**Comment by jeremypw** [comment]
Using a freshly installed flatpak of Videos (from the AppCenter) and without explicitly installing any other video related flatpak platforms, I could play an `.mp4` video from my home Video directory without problem.  I did get that error message in the terminal (or similar) but that seems unrelated.

The only video related Platform installed is
 `openh264	org.freedesktop.Platform.openh264	2.1.0	2.0	flathub	system`

This was presumably installed automatically as a dependency of Videos. (Although I also have the VLC flatpak installed so it could have come from there).

Videos was installed by default to "user" not "system". 

Does any error dialog show or does Videos just display a blank screen when playing that video?  Does this happen to videos from other sources?  Or other formats? 

Possibly due to a metadata problem (that also occurs in Photos).

**Comment by kdwk** [comment]
@jeremypw no error messages, just a blank screen. I’ll try re-installation of Videos.

**Comment by chhch** [comment]
I have the same problem with a MKV and a AVI video. Reinstalling Videos did not help me. I can play the MKV video now, but it stutters (GPU acceleration is enabled). The AVI video still does not work at all. The same videos can be played by Clapper without problem.

I downloaded and tried `sample_1280x720_surfing_with_audio` for AVI, MKV, MP4 and MPG respectively from https://filesamples.com/categories/video.

- MKV and MP4 video and audio works
- AVI only audio works
- MPG neither Video nor audio works

It seems to be because of the codec in my case. @jeremypw does the sample `sample_1280x720_surfing_with_audio.avi` and ` sample_1280x720_surfing_with_audio.mpg` work for you? Could you try?

**Comment by jeremypw** [comment]
@chhch Neither of those videos plays properly for me - the AVI one plays the sound but neither show any video.  I'll try and find out what is missing.

**Comment by jeremypw** [comment]
Maybe related - Files (using tumbler) cannot thumbnail the MP3 video but it can thumbnail the AVI one.

**Comment by jeremypw** [comment]
Strangely if I convert a (playable) MP4 video to AVI (using CloudConvert.com) then it can still be played in Videos (both video and audio).

I guess this is because AVI is a container format and different audio/video codecs can be used within it.  Compare the info obtained with `mediainfo-gui` for the original sample AVI file and the sample MP4 file converted to AVI:
![AVIinfos](https://user-images.githubusercontent.com/10513844/144407875-a6951269-e9d2-4086-852a-597e157fa289.png)

Note that I have now installed the -bad and -ugly gstreamer plugin packages using apt.  Not sure whether they are usable by a Flatpak though.

**Comment by kdwk** [comment]
> @jeremypw no error messages, just a blank screen. I’ll try re-installation of Videos.

Re-installing did not work.

**Comment by jeremypw** [comment]
I think it is likely to be due to a lack of restricted codecs oob. Some apps bundle their own codecs but Videos relies on gstreamer I thinks.

**Comment by kdwk** [comment]
@jeremypw would you be kind enough to explain to what extent is Gstreamer involved in Videos? I understand that Gstreamer is the multimedia framework for Gtk apps but I recall Danielle talking about replacing the original Clutter widget with the Gstreamer widget, so originally it wasn’t using Gstreamer? Im a bit lost.

**Comment by jeremypw** [comment]
@kdwk TBH I am not too sure about past structure of the code, but it now has direct and indirect dependencies on GStreamer (see the README.md).  The ClutterGst library only pulls in the basic (good) GStreamer plugins as far as I can see.   Interestingly, I tried compiling the master code from source and installing/running it without Flatpaking it.  It then plays both the sample AVI and MPG files.  So it looks like something to do with what codecs are available to the Flatpak.  (I have manually installed the bad and ugly gstreamer plugin packages as well as the Ubuntu restricted extras package)

**Comment by jeremypw** [comment]
I think there are legal problems in providing some codecs oob in the elementary Flatpak platform?

**Comment by Marukesu** [comment]
videos don't inherit the `org.freedesktop.Platform.ffmpeg-full` extension point, so that's probably the issue. , I believe inheriting the extension point shouldn't causes problems since we aren't downloading the codecs, just mounting then in the sandbox if installed.

**Comment by kdwk** [comment]
> videos don't inherit the org.freedesktop.Platform.ffmpeg-full extension point

Ah, so that’s why I can’t play videos even though I installed org.freedesktop.Platform.ffmpeg-full
