### ISSUE TITLE
Audience doesn't show subtitles

### ISSUE THREAD

**Issue by c3lg0n** [elementary/videos#32]
Greetings, I tried to add a sub with drag and drop or from the menu with no results. The extension is ".srt" and the video is MP4.
My system is in spanish.
Let me now what information you need.

**Comment by zhiquan-yu** [comment]
.mkv video with .ass subtitle also.

**Comment by peteruithoven** [comment]
I regularly have the same issue. 

The following pull request helps, with it's changes, it updates the External subtitle element in the settings popup: https://github.com/elementary/videos/pull/46

The subtitles don't however appear. 

Example 1: Sintel 
From: https://durian.blender.org/download/
[Sintel.2010.720p.mkv](http://ftp.nluug.nl/pub/graphics/blender/demo/movies/Sintel.2010.720p.mkv) 
[English subtitles](https://durian.blender.org/wp-content/content/subtitles/sintel_en.srt)
(This example is somewhat confusing because it already contains subtitles)
The subtitles included in this video are shown, but the external one is not. They are shown in other video players, like mpv Media Player.

I'm looking for another example that doesn't include subtitles in the file itself.

**Comment by peteruithoven** [comment]
I've made a simple example app to demonstrate the issue: https://github.com/peteruithoven/subtitles-test

It looks like it will only show the subtitles when the subtitles file has the same name as the video file.

**Comment by peteruithoven** [comment]
@artemanufrij I just noticed that your [Cinema](https://github.com/artemanufrij/playmyvideos) app also only loads external subtitles with the same name as the video file. Have you found more documentation on this possible limitation of ClutterGst?

**Comment by artemanufrij** [comment]
@peteruithoven I tested it yesterday. `set_subtitle_uri` doesn't throw an exception and it actually doesn't work. I have same behaviour like you posted. it works only if subtitle file has same name like video file. Seems like a ClutterGst bug.

**Comment by artemanufrij** [comment]
@peteruithoven and I found out if you have a subtitle file in same folder `subtitle_tracks` has a count > 0 otherwise 0

**Comment by peteruithoven** [comment]
Thanks for checking it out. I was afraid of that. I've already send an email to the mailing list, asked for help on the irc, but I've had 0 response. One of the people on irc only pointed to gstreamer.
I really don't want to interact with Gnome Bugzilla, but maybe I should...

**Comment by artemanufrij** [comment]
@peteruithoven good luck bro!

**Comment by aadilayub** [comment]
This issue persists on other video players such as VLC and Cinema 

https://elementaryos.stackexchange.com/questions/12462/videos-wont-display-subtitles
