### ISSUE TITLE
DVD menus cannot be navigated

### ISSUE THREAD

**Issue by alexgleason** [elementary/videos#81]
I'm sorta continuing off #80 but this is a different issue. Once you get into the DVD, it is not possible to click the menu buttons or navigate by keyboard.

I'm sure you all know this, but for completeness I'll add this context. Most DVDs have a menu like this that is traditionally navigated with a remote control when played on a hardware DVD player:

![sailing_around_the_world_dvd_menu](https://user-images.githubusercontent.com/3639540/40383005-bfd6e5dc-5dcd-11e8-9d48-64c7f0c439a2.png)

In order to actually play the movie, you have to use arrow buttons to highlight "Play" then press enter. Or you can watch special features, configure subtitles, or whatever.

This menu shows up in Videos when you play a DVD, but you **cannot progress past it.** There are a few reasons for this, it seems:

1. Clicking the video allows you to drag its window around the screen. This seems to override any ability you'd have to activate a menu button with the cursor.
2. The arrow keys seek the video forward/back, it doesn't move the menu selection like you'd expect.
3. Pressing "space" or "enter" acts like play/pause instead of the "OK" button on a DVD remote.

**Comment by eric0001** [comment]
The packages ubuntu-restricted-extras and libdvd-pkg are installed and the command sudo dpkg-reconfigure libdvd-pkg has been executed.
When running the following command in the terminal
gst-play-1.0 dvd://
I am perfectly able on elementary OS loki to navigate the DVD menu with the mouse cursor. What's missing with this method is the ability to skip forward or backward while playing a DVD movie.
So gst-play-1.0 is a tool based on gstreamer-1.0 if I'm not mistaken; so why can it not be fixed in audience (aka pantheon-videos)? I don't understand. There seems to be no bug in gstreamer-1.0.
